### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [Halodi/halodi-unity-package-registry-manager#1]
Hi @jespersmith,

Thanks for making this awesome UPM package. I'm the creator of the [OpenUPM](https://openupm.com) platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 300+ open-source UPM packages at the time of writing.

I think it would be useful if you included this in our registry. To make it happen, I would suggest you make GitHub releases (which create Git tags v0.0.1) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

After your GitHub release, our build pipelines will detect the changes and build UPM packages in 5-10 minutes. Then you can visit your package at https://openupm.com/packages/com.halodi.halodi-unity-package-registry-manager/

Hopeful this makes sense for you. And feel free to submit more open-source UPM packages at https://openupm.com/packages/add/.

**Comment by jespersmith** [comment]
hi @favoyang 

I see you already added the package. Making release tags is good practice and I fully support that. I've added a tag for the initial release (0.0.2).

I'm using this package in conjunction with https://github.com/Halodi/halodi-unity-package-creator which I also open sourced. This package allows you to create a number of packages inside a Unity project and maintain/publish them easily. I'm open to talking about how to integrate that with OpenUPM.

**Comment by favoyang** [comment]
Thank you for the quick response. I have checked the halodi-unity-package-creator package, a good tool to maintain UPM package locally (push mode)

OpenUPM is working differently. It won't do any custom build, instead, we suggest package owners use CI like GitHub actions to handle extra build processes like DLL compiling or handling sample folder. Then it pulls Git tags and bundle package on the cloud (pull mode).

I wish both tools can get benefits from each other. Well creating a UPM package is already a huge help. But to work with OpenUPM, we still require a working Git tag. I can see two ways to make it work:
- Adding a "Create GitHub Releases / Versioned Git Tag" feature. When you publish to a registry, you can optionally force push content to a versioned Git Tag.
- Help the user set up a simple GitHub action to split the UPM branch (and handle samples correctly). Like this one https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4

Make OpenUPM support push mode is also a solution, but it's not my current focus, it breaks too many things.
