### ISSUE TITLE
How to fully remove credentials

### ISSUE THREAD

**Issue by hybridherbst** [Halodi/halodi-unity-package-registry-manager#10]
Even after removing credentials via this manager and cleaning the project package cache and Unity's package cache, it seems that I'm still authorized to download packages with an earlier authorization.

Are there extra steps needed to remove authorization besides doing it through the manager?

Steps to reproduce:
1) authorize for a GitHub package or another thing that needs auth to download
2) install package (should work)
3) uninstall package, remove from library package cache, remove from unity package cache
4) remove credentials
5) try to install package (should fail, but works)

**Comment by jespersmith** [comment]
Are the credentials still in [HOME]/.upmconfig.toml after removing them from the manager?

**Comment by hybridherbst** [comment]
No, that file is empty as expected.

**Comment by jespersmith** [comment]
I don't think I can fix it on my side, and this should be filed as a big in unity. Did you try restarting?

**Comment by hybridherbst** [comment]
I'd recommend leaving the issue open for others to see since it's still an open issue. You can label it as "not-this-project".
I'll report a bug with Unity and note here if something comes back from them.

Do you see the same behaviour?

**Comment by jespersmith** [comment]
There seem to be 3 locations that store cached versions of the package

- [project]/Library/PackageCache
- ~/.config/unity3d/cache/npm/[host]/*
- ~/.config.unity3d/cache/packages/[host]/*

After removing all three, it will not be able to load the package anymore. Another test is to publish a new package and try adding that after removing the credential.

**Comment by hybridherbst** [comment]
OK, seems to work that way. I was only aware of the "packages" cache and not the additional duplicate storage in "npm", not sure why it is that way but ok. Cleaning the package from all locations properly shows an authentication issue as it should :) Thanks!
