### ISSUE TITLE
[Discussion] Make some methods public to allow use as "Credentials API"

### ISSUE THREAD

**Issue by hybridherbst** [Halodi/halodi-unity-package-registry-manager#13]
For a current project we'd want to explicitly ask if specific credentials are already set, and add them if not.
The former already works via the CredentialManager, but the methods for the latter are strictly internal.

I can do a PR for changing this to allow for "API-style" usage (so, for example, other more specific credential windows can be implemented by other packages), however, I wanted to discuss first if you have something against this or specific remarks why you've built it the current way :)

**Comment by jespersmith** [comment]
Please make a PR, I do not think I had a very good reason to make these methods private.

**Comment by jespersmith** [comment]
Solved by making all core functionality public: https://github.com/Halodi/halodi-unity-package-registry-manager/commit/d1d335690d0f513b974f5c5f5a49292c249fcc4b
