### ISSUE TITLE
[Suggestion] Restarting the editor after adding credentials

### ISSUE THREAD

**Issue by StephenHodgson** [Halodi/halodi-unity-package-registry-manager#14]
Hi, really great tool, thanks for this.

I would like to suggest asking the developer if they'd like to restart the editor after adding the credentials. This would help in cases when people forget, or if they'd like to skip the manual steps.

**Comment by StephenHodgson** [comment]
Actually after testing, it seems we don't actually have to restart the editor, just refresh the packages.

**Comment by hybridherbst** [comment]
I believe it depends on the Unity version; in some you just can call Client.Resolve() and get proper refresh, but especially in earlier versions that isn't enough. Which version did you test on?

**Comment by StephenHodgson** [comment]
2019.4.12f1
