### ISSUE TITLE
Prefixed dlls cause warnings in build

### ISSUE THREAD

**Issue by StephenHodgson** [Halodi/halodi-unity-package-registry-manager#16]
Hi there, we're experiencing the following warnings while building our applications using this package:

![image](https://user-images.githubusercontent.com/13334553/97221172-cb145d80-1789-11eb-9943-50fa2436f5b7.png)

```
Assembly 'Newtonsoft.Json' has non matching file name: '860BB79D.Newtonsoft.Json.dll'. This can cause build issues on some platforms.
Assembly 'ICSharpCode.SharpZipLib' has non matching file name: '860BB79D.SharpZipLib.dll'. This can cause build issues on some platforms.
Assembly 'Tomlyn' has non matching file name: '860BB79D.Tomlyn.dll'. This can cause build issues on some platforms.
```

## Project Settings:

- Unity 2019.4.13f1
- Windows64 Build Target
- .NET Standard 2.0
- IL2CPP

**Comment by hybridherbst** [comment]
I reported this as a bug to Unity recently. 

Jesper prefixed the DLLs to avoid collisions as in Unity multiple DLLs with the same assembly name are pretty common (different file names solve that, but on some build platforms that's not allowed - in editor it's totally fine).

I believe it's a bug that Unity warns on build about Editor-only DLLs; the case is
(1287359 - [Builds] Warning around non-matching assembly names is logged on build for editor-only assemblies)
and I'm still waiting for a QA response.

**Comment by jespersmith** [comment]
Not sure how to fix the Tomlyn issue. I can unpack Tomlyn and make an assembly reference instead, which would solve this warning. Not sure about the disadvantages.

**Comment by StephenHodgson** [comment]
Could we just get rid of the prefix?

ISharpZipLib still has warnings but I think that needs to be solved in their package. [Opened a issue there for it](https://github.com/icsharpcode/SharpZipLib/issues/540).

**Comment by jespersmith** [comment]
As these packages are only used in Editor mode, I do think the warning is a Unity bug.

While I agree that in an ideal world we would not get any warnings during leaving this warning solves more problems than it causes. You should be able to make a rule in your CI stack to ignore the warning.

**Comment by StephenHodgson** [comment]
Ignoring warnings is lazy lol.

**Comment by StephenHodgson** [comment]
It's all good. Seems to be a bug in Unity's package anyway. I'm sure they'll fix it eventually (**_heavy sarcasm_**)

**Comment by jespersmith** [comment]
> Ignoring warnings is lazy lol.

While in general this is true, I think there are cornercases where the warning is in error and trying to hide it results in more problems.

**Comment by StephenHodgson** [comment]
Could we at least keep this open until we figure out what to do with `Tomlyn`?

**Comment by StephenHodgson** [comment]
Ideally the real fix here is getting Unity to appropriately handle multiple dll assemblies identified in the project.

**Comment by hybridherbst** [comment]
Yeah, they've been fighting with this for years, hence the "nuget wrappers" on their registry because they want to avoid name clashes in their own stuff.

Re ICSharpCode: I'll report a bug to Unity.
Re Tomlyn: two short-term options; dropping the prefix (potentially causing issues with other packages) or embedding the Tomlyn source again... I'd prefer the medium-term solution of Unity fixing the warning bug for editor-only asmdefs.
