### ISSUE TITLE
console error after installing this package in unity 2019.3.14f1

### ISSUE THREAD

**Issue by hannesdelbeke** [Halodi/halodi-unity-package-registry-manager#24]
i got the following console error after installing this package
`
    Library\PackageCache\com.unity.sharp-zip-lib@1.2.2-preview.1\Runtime\Utils\ZipUtility.cs(97,66): error CS0433: The type 'ZipOutputStream' exists in both 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' and 'ICSharpCode.SharpZipLib, Version=1.2.0.246, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'
`

**Comment by hannesdelbeke** [comment]
this seems to be related to the dependencies of this package
i'm running this in a test project so it likely clashes with the dependencies of one of the unity built in packages
![image](https://user-images.githubusercontent.com/3758308/105750195-52fe3500-5f3c-11eb-81d0-73c101f54f5c.png)

**Comment by hybridherbst** [comment]
Would you be able to post your manifest here so it's clear which packages you already have?

**Comment by hannesdelbeke** [comment]
it seems it clashes with this package, which has no dependencies

`"uk.co.mediatonic.unity-package-extractor": "https://github.com/mediatonic/UnityPackageExtractor.git",`

**Comment by hannesdelbeke** [comment]
when i unstall that package, or yours, the error dissapears
for now i'll uninstall the other package since i don't need it atm

**Comment by hannesdelbeke** [comment]
ah it's prob the way the other package has been packed, it includes the ICSharpcode dll in the package directly
