### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path on SharpZipLib

### ISSUE THREAD

**Issue by bdovaz** [Halodi/halodi-unity-package-registry-manager#3]
Unity 2019.3.15f1.

I get the following error when importing this package via OpenUPM:

DirectoryNotFoundException: Could not find a part of the path

{UNITY_PROJECT_PATH}\Library\PackageCache\com.halodi.halodi-unity-package-registry-manager@0.0.3\ThirdParty\SharpZipLib\com.halodi.halodi-unity-package-registry-manager.ICSharpCode.SharpZipLib.dll"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <437ba245d8404784b9fbab9b439ac908>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) (at <28cdca1704d2491781795499c297b78b>:0)

**Comment by jespersmith** [comment]
Thank you for this bug report. I'm not able to reproduce on my system, however I've a few ideas

Can you check the following for me

- Windows default maximum path lengths are 260 characters (my system is setup for longer paths for Java development). How many characters is your {UNITY_PROJECT_PATH}? If longer than about 83 characters, it might fail.

-  If UNITY_PROJECT_PATH is short,  can you add the repository using a git url as described in the readme?

**Comment by jespersmith** [comment]
I've pushed a new version (0.0.4) that reduces the path name length for the thirdparty dependencies. That might avoid the issue for more users

**Comment by jespersmith** [comment]
The previous fix missed a reference in the asmdef (requires a Unity restart to show up). I've pushed 0.0.5 to fix.
