### ISSUE TITLE
Unclear usage for GitHub package read access

### ISSUE THREAD

**Issue by soraryu** [Halodi/halodi-unity-package-registry-manager#4]
After reading your post at https://forum.unity.com/threads/npm-registry-authentication.836308/#post-5884289 I immediately tried it out, thanks for building this!

However, it was unclear how to use it:
- I tried signing in with "get login token" to GitHub with a personal access token; 
- got warning "needs read:packages", resolved that
- got warning "needs write:packages", not sure why, but resolved that
- got error "The expected resourve was not found".

Then I used the token directly, and that surprisingly worked - would be great if you could clarify that a bit better, thank you!

**Comment by jespersmith** [comment]
Thank you for bringing this to our attention.

I updated the README file with provider-specific instructions in commit #80065e5. If still unclear, please let me know.

**Comment by soraryu** [comment]
Thanks for clarifying. 
I'd say this is partially answered - if people just want to consume a package (not develop on it) then read:packages should be enough, which you might want to add to the Readme as well.
